const express=require("express")
const app=express()
app.set("view engine","ejs")
// const usermodal = require("./Modal/user")
const db=require("./config/db")
const cookieParser = require('cookie-parser')
const U_router = require("./Routes/userroutes")
const P_router = require("./Routes/productroutes")
const C_router = require("./Routes/categoryroutes")
const passport=require("passport")
const session=require("express-session")
const LocalAuth = require("./middleware/Localauth")

app.use(session({secret:'keyboard cat',resave:true,saveUninitialized:true}))
LocalAuth(passport)
app.use(passport.initialize())
app.use(passport.session())
app.use(express.urlencoded())
app.use(express.json())
app.use(cookieParser());
app.use(express.urlencoded())
app.use("/user",U_router)
app.use("/pro",P_router)
app.use("/category",C_router)

app.listen(4004,()=>{
    console.log('server listen')
})